#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyExchanger
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FOREXMoney")]
	public partial class LinqMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblCurrency(TblCurrency instance);
    partial void UpdateTblCurrency(TblCurrency instance);
    partial void DeleteTblCurrency(TblCurrency instance);
    #endregion
		
		public LinqMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ForexMoneyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblCurrency> TblCurrencies
		{
			get
			{
				return this.GetTable<TblCurrency>();
			}
		}
		
		public System.Data.Linq.Table<tblCompany> tblCompanies
		{
			get
			{
				return this.GetTable<tblCompany>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMasterCurrencyCodes")]
		public ISingleResult<GetMasterCurrencyCodesResult> GetMasterCurrencyCodes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMasterCurrencyCodesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetLocationCurrency")]
		public ISingleResult<GetLocationCurrencyResult> GetLocationCurrency([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationCode", DbType="VarChar(20)")] string locationCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrencyCode", DbType="VarChar(20)")] string currencyCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), locationCode, currencyCode);
			return ((ISingleResult<GetLocationCurrencyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveTransaction")]
		public ISingleResult<SaveTransactionResult> SaveTransaction([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(20)")] string createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrencyCode", DbType="VarChar(20)")] string currencyCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TranType", DbType="VarChar(1)")] string tranType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rate", DbType="Decimal(18,8)")] System.Nullable<decimal> rate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FAmount", DbType="Money")] System.Nullable<decimal> fAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LAmount", DbType="Money")] System.Nullable<decimal> lAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Avgcost", DbType="Money")] System.Nullable<decimal> avgcost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AvgStock", DbType="Float")] System.Nullable<double> avgStock)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), createdBy, currencyCode, tranType, rate, fAmount, lAmount, avgcost, avgStock);
			return ((ISingleResult<SaveTransactionResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblCurrency")]
	public partial class TblCurrency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CurrencyCode;
		
		private string _CurrencyName;
		
		private string _Major;
		
		private string _Minor;
		
		private System.Nullable<char> _LocalCurrency;
		
		private System.Nullable<double> _Varience;
		
		private System.Nullable<double> _BuyRate;
		
		private System.Nullable<double> _SellRate;
		
		private System.Nullable<decimal> _Units;
		
		private System.Nullable<double> _Stock;
		
		private System.Nullable<decimal> _AvgCost;
		
		private System.Nullable<System.DateTime> _LastPdate;
		
		private System.Nullable<System.DateTime> _LastSDate;
		
		private System.Nullable<char> _TTCurrency;
		
		private string _TTCustomerCode;
		
		private System.Nullable<char> _TTCustomerUpdate;
		
		private System.Nullable<char> _OPERATOR;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCurrencyCodeChanging(string value);
    partial void OnCurrencyCodeChanged();
    partial void OnCurrencyNameChanging(string value);
    partial void OnCurrencyNameChanged();
    partial void OnMajorChanging(string value);
    partial void OnMajorChanged();
    partial void OnMinorChanging(string value);
    partial void OnMinorChanged();
    partial void OnLocalCurrencyChanging(System.Nullable<char> value);
    partial void OnLocalCurrencyChanged();
    partial void OnVarienceChanging(System.Nullable<double> value);
    partial void OnVarienceChanged();
    partial void OnBuyRateChanging(System.Nullable<double> value);
    partial void OnBuyRateChanged();
    partial void OnSellRateChanging(System.Nullable<double> value);
    partial void OnSellRateChanged();
    partial void OnUnitsChanging(System.Nullable<decimal> value);
    partial void OnUnitsChanged();
    partial void OnStockChanging(System.Nullable<double> value);
    partial void OnStockChanged();
    partial void OnAvgCostChanging(System.Nullable<decimal> value);
    partial void OnAvgCostChanged();
    partial void OnLastPdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPdateChanged();
    partial void OnLastSDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSDateChanged();
    partial void OnTTCurrencyChanging(System.Nullable<char> value);
    partial void OnTTCurrencyChanged();
    partial void OnTTCustomerCodeChanging(string value);
    partial void OnTTCustomerCodeChanged();
    partial void OnTTCustomerUpdateChanging(System.Nullable<char> value);
    partial void OnTTCustomerUpdateChanged();
    partial void OnOPERATORChanging(System.Nullable<char> value);
    partial void OnOPERATORChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    #endregion
		
		public TblCurrency()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this.OnCurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._CurrencyCode = value;
					this.SendPropertyChanged("CurrencyCode");
					this.OnCurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyName", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string CurrencyName
		{
			get
			{
				return this._CurrencyName;
			}
			set
			{
				if ((this._CurrencyName != value))
				{
					this.OnCurrencyNameChanging(value);
					this.SendPropertyChanging();
					this._CurrencyName = value;
					this.SendPropertyChanged("CurrencyName");
					this.OnCurrencyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Major", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Major
		{
			get
			{
				return this._Major;
			}
			set
			{
				if ((this._Major != value))
				{
					this.OnMajorChanging(value);
					this.SendPropertyChanging();
					this._Major = value;
					this.SendPropertyChanged("Major");
					this.OnMajorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Minor
		{
			get
			{
				return this._Minor;
			}
			set
			{
				if ((this._Minor != value))
				{
					this.OnMinorChanging(value);
					this.SendPropertyChanging();
					this._Minor = value;
					this.SendPropertyChanged("Minor");
					this.OnMinorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalCurrency", DbType="Char(1)")]
		public System.Nullable<char> LocalCurrency
		{
			get
			{
				return this._LocalCurrency;
			}
			set
			{
				if ((this._LocalCurrency != value))
				{
					this.OnLocalCurrencyChanging(value);
					this.SendPropertyChanging();
					this._LocalCurrency = value;
					this.SendPropertyChanged("LocalCurrency");
					this.OnLocalCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varience", DbType="Float")]
		public System.Nullable<double> Varience
		{
			get
			{
				return this._Varience;
			}
			set
			{
				if ((this._Varience != value))
				{
					this.OnVarienceChanging(value);
					this.SendPropertyChanging();
					this._Varience = value;
					this.SendPropertyChanged("Varience");
					this.OnVarienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyRate", DbType="Float")]
		public System.Nullable<double> BuyRate
		{
			get
			{
				return this._BuyRate;
			}
			set
			{
				if ((this._BuyRate != value))
				{
					this.OnBuyRateChanging(value);
					this.SendPropertyChanging();
					this._BuyRate = value;
					this.SendPropertyChanged("BuyRate");
					this.OnBuyRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellRate", DbType="Float")]
		public System.Nullable<double> SellRate
		{
			get
			{
				return this._SellRate;
			}
			set
			{
				if ((this._SellRate != value))
				{
					this.OnSellRateChanging(value);
					this.SendPropertyChanging();
					this._SellRate = value;
					this.SendPropertyChanged("SellRate");
					this.OnSellRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Units", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				if ((this._Units != value))
				{
					this.OnUnitsChanging(value);
					this.SendPropertyChanging();
					this._Units = value;
					this.SendPropertyChanged("Units");
					this.OnUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Float")]
		public System.Nullable<double> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgCost", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> AvgCost
		{
			get
			{
				return this._AvgCost;
			}
			set
			{
				if ((this._AvgCost != value))
				{
					this.OnAvgCostChanging(value);
					this.SendPropertyChanging();
					this._AvgCost = value;
					this.SendPropertyChanged("AvgCost");
					this.OnAvgCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPdate
		{
			get
			{
				return this._LastPdate;
			}
			set
			{
				if ((this._LastPdate != value))
				{
					this.OnLastPdateChanging(value);
					this.SendPropertyChanging();
					this._LastPdate = value;
					this.SendPropertyChanged("LastPdate");
					this.OnLastPdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastSDate
		{
			get
			{
				return this._LastSDate;
			}
			set
			{
				if ((this._LastSDate != value))
				{
					this.OnLastSDateChanging(value);
					this.SendPropertyChanging();
					this._LastSDate = value;
					this.SendPropertyChanged("LastSDate");
					this.OnLastSDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTCurrency", DbType="Char(1)")]
		public System.Nullable<char> TTCurrency
		{
			get
			{
				return this._TTCurrency;
			}
			set
			{
				if ((this._TTCurrency != value))
				{
					this.OnTTCurrencyChanging(value);
					this.SendPropertyChanging();
					this._TTCurrency = value;
					this.SendPropertyChanged("TTCurrency");
					this.OnTTCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTCustomerCode", DbType="Char(20)")]
		public string TTCustomerCode
		{
			get
			{
				return this._TTCustomerCode;
			}
			set
			{
				if ((this._TTCustomerCode != value))
				{
					this.OnTTCustomerCodeChanging(value);
					this.SendPropertyChanging();
					this._TTCustomerCode = value;
					this.SendPropertyChanged("TTCustomerCode");
					this.OnTTCustomerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTCustomerUpdate", DbType="Char(1)")]
		public System.Nullable<char> TTCustomerUpdate
		{
			get
			{
				return this._TTCustomerUpdate;
			}
			set
			{
				if ((this._TTCustomerUpdate != value))
				{
					this.OnTTCustomerUpdateChanging(value);
					this.SendPropertyChanging();
					this._TTCustomerUpdate = value;
					this.SendPropertyChanged("TTCustomerUpdate");
					this.OnTTCustomerUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATOR", DbType="Char(1)")]
		public System.Nullable<char> OPERATOR
		{
			get
			{
				return this._OPERATOR;
			}
			set
			{
				if ((this._OPERATOR != value))
				{
					this.OnOPERATORChanging(value);
					this.SendPropertyChanging();
					this._OPERATOR = value;
					this.SendPropertyChanged("OPERATOR");
					this.OnOPERATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCompany")]
	public partial class tblCompany
	{
		
		private string _Description;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Postalcode;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Email;
		
		private string _url;
		
		private string _TaxRef;
		
		private System.Nullable<decimal> _TaxPerc;
		
		private System.Nullable<decimal> _MassLimit;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedDate;
		
		private string _ModifiedBy;
		
		private System.DateTime _ModifiedDate;
		
		private System.Nullable<char> _roundoff;
		
		public tblCompany()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="Char(50)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postalcode", DbType="Char(20)")]
		public string Postalcode
		{
			get
			{
				return this._Postalcode;
			}
			set
			{
				if ((this._Postalcode != value))
				{
					this._Postalcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Char(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="Char(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="Char(20)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRef", DbType="Char(20)")]
		public string TaxRef
		{
			get
			{
				return this._TaxRef;
			}
			set
			{
				if ((this._TaxRef != value))
				{
					this._TaxRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPerc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPerc
		{
			get
			{
				return this._TaxPerc;
			}
			set
			{
				if ((this._TaxPerc != value))
				{
					this._TaxPerc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MassLimit", DbType="Money")]
		public System.Nullable<decimal> MassLimit
		{
			get
			{
				return this._MassLimit;
			}
			set
			{
				if ((this._MassLimit != value))
				{
					this._MassLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roundoff", DbType="Char(1)")]
		public System.Nullable<char> roundoff
		{
			get
			{
				return this._roundoff;
			}
			set
			{
				if ((this._roundoff != value))
				{
					this._roundoff = value;
				}
			}
		}
	}
	
	public partial class GetMasterCurrencyCodesResult
	{
		
		private string _Code;
		
		private string _Description;
		
		public GetMasterCurrencyCodesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class GetLocationCurrencyResult
	{
		
		private string _LocationCode;
		
		private string _CurrencyCode;
		
		private System.Nullable<double> _Varience;
		
		private System.Nullable<double> _Stock;
		
		private System.Nullable<double> _BuyRate;
		
		private System.Nullable<double> _SellRate;
		
		private System.Nullable<decimal> _Units;
		
		private System.Nullable<decimal> _AvgCost;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		public GetLocationCurrencyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LocationCode
		{
			get
			{
				return this._LocationCode;
			}
			set
			{
				if ((this._LocationCode != value))
				{
					this._LocationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varience", DbType="Float")]
		public System.Nullable<double> Varience
		{
			get
			{
				return this._Varience;
			}
			set
			{
				if ((this._Varience != value))
				{
					this._Varience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Float")]
		public System.Nullable<double> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyRate", DbType="Float")]
		public System.Nullable<double> BuyRate
		{
			get
			{
				return this._BuyRate;
			}
			set
			{
				if ((this._BuyRate != value))
				{
					this._BuyRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellRate", DbType="Float")]
		public System.Nullable<double> SellRate
		{
			get
			{
				return this._SellRate;
			}
			set
			{
				if ((this._SellRate != value))
				{
					this._SellRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Units", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				if ((this._Units != value))
				{
					this._Units = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgCost", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> AvgCost
		{
			get
			{
				return this._AvgCost;
			}
			set
			{
				if ((this._AvgCost != value))
				{
					this._AvgCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
	}
	
	public partial class SaveTransactionResult
	{
		
		private decimal _TranNo;
		
		private System.DateTime _TranDate;
		
		private string _DocType;
		
		private string _RefNo;
		
		private string _PPNo;
		
		private string _Name;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _Address4;
		
		private string _Nationality;
		
		private string _CustName;
		
		private string _CustCode;
		
		private System.Nullable<char> _OwnOutletYesNo;
		
		private string _LocationCode;
		
		private string _Remarks;
		
		private System.Nullable<decimal> _TTRefNo;
		
		private char _Deleted;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _dob;
		
		private string _company;
		
		public SaveTransactionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranNo", DbType="Decimal(18,0) NOT NULL")]
		public decimal TranNo
		{
			get
			{
				return this._TranNo;
			}
			set
			{
				if ((this._TranNo != value))
				{
					this._TranNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranDate", DbType="DateTime NOT NULL")]
		public System.DateTime TranDate
		{
			get
			{
				return this._TranDate;
			}
			set
			{
				if ((this._TranDate != value))
				{
					this._TranDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocType", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string DocType
		{
			get
			{
				return this._DocType;
			}
			set
			{
				if ((this._DocType != value))
				{
					this._DocType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNo", DbType="VarChar(20)")]
		public string RefNo
		{
			get
			{
				return this._RefNo;
			}
			set
			{
				if ((this._RefNo != value))
				{
					this._RefNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPNo", DbType="VarChar(20)")]
		public string PPNo
		{
			get
			{
				return this._PPNo;
			}
			set
			{
				if ((this._PPNo != value))
				{
					this._PPNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(60)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(60)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(60)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(60)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this._Address3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address4", DbType="VarChar(60)")]
		public string Address4
		{
			get
			{
				return this._Address4;
			}
			set
			{
				if ((this._Address4 != value))
				{
					this._Address4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this._Nationality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustName", DbType="Char(50)")]
		public string CustName
		{
			get
			{
				return this._CustName;
			}
			set
			{
				if ((this._CustName != value))
				{
					this._CustName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCode", DbType="VarChar(20)")]
		public string CustCode
		{
			get
			{
				return this._CustCode;
			}
			set
			{
				if ((this._CustCode != value))
				{
					this._CustCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnOutletYesNo", DbType="Char(1)")]
		public System.Nullable<char> OwnOutletYesNo
		{
			get
			{
				return this._OwnOutletYesNo;
			}
			set
			{
				if ((this._OwnOutletYesNo != value))
				{
					this._OwnOutletYesNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCode", DbType="VarChar(20)")]
		public string LocationCode
		{
			get
			{
				return this._LocationCode;
			}
			set
			{
				if ((this._LocationCode != value))
				{
					this._LocationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(50)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTRefNo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TTRefNo
		{
			get
			{
				return this._TTRefNo;
			}
			set
			{
				if ((this._TTRefNo != value))
				{
					this._TTRefNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Char(1) NOT NULL")]
		public char Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this._Deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="VarChar(20)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="VarChar(12)")]
		public string dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this._dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="VarChar(1)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this._company = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
